services:
  structurizr:
    build:
      context: ..
      dockerfile: architecture/Dockerfile
      target: dev
    user: "0"
    volumes:
      - ..:/repo:ro
      - ./structurizr:/usr/local/structurizr
      - ./adrs:/usr/local/structurizr/adrs
      - ./scripts/prepare_structurizr_content.py:/usr/local/bin/prepare_structurizr_content.py:ro
    ports:
      - "8080:8080"
