services:
  structurizr:
    image: structurizr/structurizr:latest
    user: "0"
    command: local
    ports:
      - "8080:8080"
    volumes:
      - ./structurizr:/usr/local/structurizr
      - ./adrs:/usr/local/adrs

