FROM node:24-alpine

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .
COPY policies/user/role-catalog.json ./policies/user/role-catalog.json

EXPOSE 5173

CMD ["pnpm", "run", "dev"]
